packages:
    - 'libs/**/*'
    - 'apps/*'

# 依赖版本目录（Catalogs）
# 在 monorepo 内统一维护依赖版本，子包通过 "catalog:" 引用。
# @see https://pnpm.io/catalogs#defining-catalogs
catalog:
    # NestJS
    '@nestjs/common': '^11.0.1'
    '@nestjs/core': '^11.0.1'
    '@nestjs/config': '^4.0.0'
    '@nestjs/platform-fastify': '^11.0.1'
    '@nestjs/testing': '^11.0.1'
    '@nestjs/cli': '^11.0.0'
    '@nestjs/schematics': '^11.0.0'
    '@nestjs/terminus': '^11.0.0'
    '@nestjs/jwt': '^10.2.0'
    '@nestjs/passport': '^10.0.3'
    '@nestjs/swagger': '^11.2.5'
    passport: '^0.7.0'
    passport-jwt: '^4.0.1'

    # Runtime
    '@fastify/static': '^9.0.0'
    '@fastify/cookie': '^11.0.0'
    nestjs-cls: '^5.4.2'
    reflect-metadata: '^0.2.2'
    rxjs: '^7.8.1'
    ioredis: '^5.5.0'
    redlock: '^4.2.0'
    nestjs-i18n: '^10.6.0'
    class-validator: '^0.14.1'
    class-transformer: '^0.5.1'
    '@mikro-orm/core': '6.1.1'
    '@mikro-orm/cli': '6.1.1'
    '@mikro-orm/migrations': '6.1.1'
    '@mikro-orm/nestjs': '6.1.1'
    '@mikro-orm/postgresql': '6.1.1'
    pg: '^8.13.3'
    argon2: '^0.40.3'

    # Authorization（CASL）
    '@casl/ability': '^6.7.1'

    # Types
    '@types/node': '^22.10.7'

    # Logging
    nestjs-pino: '^4.5.0'
    pino: '^10.3.1'
    pino-pretty: '^13.1.3'
